#!/bin/sh

# -o pipefail on bash only
if [ -n "$BASH" ]; then
		set -o pipefail
fi

set -eu

# Run unit tests for each module
echo "Running unit tests"
zig build test

# Download the results.json file from the main branch on github, and compare with the current results.json file
echo "Downloading results.json from main branch on GH"
curl https://raw.githubusercontent.com/srijan-paul/jam/refs/heads/main/tools/results.json -o ./results-old.json
echo "Comparing results.json files"
zig build test-262 -- --compare ./results-old.json
rm ./results-old.json

