name: tc39/test262-parser-tests 
run-name: Run all the test262-parser-tests, and ensure there is no regression 
on:
  push:
    branches:
      - '**' 

env:
  JAM_TESTS_262_DIR: ${{ github.workspace }}/test262-parser-tests

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - name: Clone tc39 parser tests
        run: |
          git clone --depth 1 https://github.com/tc39/test262-parser-tests
      - name: Install zig 
        uses: mlugg/setup-zig@v2
        with:
          version: master 
      - name: Run the tests
        run: zig build test-262 -- --compare ./tools/results.json

