name: Run unit tests
run-name: Run all unit tests in the project
on:
  push:
    branches:
      - '**' 

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master 
      - run: zig build test
